version: 2.1

parameters:
  helm-deploy:
    type: boolean
    default: false

  tf-deploy:
    type: boolean
    default: false

jobs:
  tf-job:
     docker:
        - image: cimg/base:stable
     steps:
       - run: echo "hello"
       
  helm-job:
     docker:
        - image: cimg/base:stable
     steps:
       - run: echo "hello"

workflows:
  terraform-deploy:
    when: 
      and: 
       - equal: [true, << pipeline.parameters.tf-deploy >>]
    jobs:
      - tf-job

  helm-deploy:
    when: 
      and: 
       - equal: [true, << pipeline.parameters.helm-deploy >>]
    jobs:
      - helm-job
