version: 2.1

parameters:
  helm-deploy:
    type: boolean
    default: false

  tf-deploy:
    type: boolean
    default: false

jobs:
  simple-job:
     docker:
        - image: cimg/base:stable
     steps:
       - run: echo "hello"

workflows:
  terraform-deploy:
    when: 
      and: 
       - equal: ["main", << pipeline.git.branch >> ]
       - equal: [true, << pipeline.parameters.tf-deploy >>]
    jobs:
      - simple-job

  helm-deploy:
    when: 
      and: 
       - equal: ["main", << pipeline.git.branch >> ]
       - equal: [true, << pipeline.parameters.helm-deploy >>]
    jobs:
      - simple-job
